[package]
name = "wikipedia-comedy-scraper-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
csv = "1.2.2"
log = "0.4.19"
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.17.1"
